import 'academic_models.dart';

const fallbackSupervisors = <AcademicSupervisor>[
  AcademicSupervisor(
    name: 'أ.د. عادل محمود',
    university: 'جامعة القاهرة',
    speciality: 'هندسة مدنية ونانو',
    bio: 'مخترع وباحث في تكنولوجيا المواد الدقيقة والنانو.',
    faculty: 'كلية الهندسة',
    category: 'Engineering',
    tags: ['هندسة', 'مدني', 'نانو', 'مواد'],
    methodologies: ['كمي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'د. هدى الشافعي',
    university: 'جامعة عين شمس',
    speciality: 'هندسة معمارية وذكاء اصطناعي',
    bio: 'متخصصة في معالجة اللغات الطبيعية والتعلم العميق.',
    faculty: 'كلية الهندسة',
    category: 'Engineering',
    tags: ['هندسة', 'معماري', 'ذكاء', 'حاسب'],
    methodologies: ['كمي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'أ.د. سارة علي',
    university: 'جامعة الملك سعود',
    speciality: 'كيمياء عضوية',
    bio: 'أبحاث متقدمة في الكيمياء العضوية والتطبيقات الطبية.',
    faculty: 'كلية العلوم',
    category: 'Science',
    tags: ['كيمياء', 'علوم', 'طب', 'تحليل'],
    methodologies: ['كمي'],
  ),
  AcademicSupervisor(
    name: 'أ.د. مجدي يعقوب',
    university: 'مركز القلب',
    speciality: 'جراحة قلب',
    bio: 'خبير في جراحات القلب المعقدة والأبحاث السريرية.',
    faculty: 'كلية الطب',
    category: 'Medicine',
    tags: ['طب', 'قلب', 'جراحة', 'سريري'],
    methodologies: ['كمي', 'نوعي'],
  ),
  AcademicSupervisor(
    name: 'المستشار أحمد فتحي',
    university: 'جامعة القاهرة',
    speciality: 'قانون دولي',
    bio: 'خبرة واسعة في القانون الدولي والتحكيم.',
    faculty: 'كلية الحقوق',
    category: 'Law',
    tags: ['قانون', 'دولي', 'حقوق'],
    methodologies: ['نوعي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'أ.د. محمد أحمد',
    university: 'جامعة القاهرة',
    speciality: 'ذكاء اصطناعي وعلم بيانات',
    bio: 'خبير في تحليل البيانات الضخمة والرؤية الحاسوبية.',
    faculty: 'كلية الحاسبات',
    category: 'CS',
    tags: ['ذكاء', 'بيانات', 'حاسب', 'برمجة'],
    methodologies: ['كمي'],
  ),
];

const fallbackResearchIdeas = <AcademicResearchIdea>[
  AcademicResearchIdea(
    title: 'نظام مرور ذكي',
    provider: 'وزارة النقل',
    details: 'تطوير خوارزميات للتحكم في الإشارات وتحليل حركة المرور.',
    tags: ['مرور', 'ذكاء', 'هندسة', 'تحكم'],
    budget: '15,000 ج.م',
    votesCount: 12,
    proposalsCount: 4,
  ),
  AcademicResearchIdea(
    title: 'طاقة شمسية',
    provider: 'شركة الكهرباء',
    details: 'دراسة تأثير الحرارة على كفاءة الألواح الشمسية.',
    tags: ['طاقة', 'شمسية', 'هندسة', 'كهرباء'],
    budget: '10,000 ج.م',
    votesCount: 8,
    proposalsCount: 2,
  ),
  AcademicResearchIdea(
    title: 'تطبيقات النانو في الطب',
    provider: 'مركز الأبحاث الطبية',
    details: 'استخدام تقنيات النانو في التشخيص المبكر.',
    tags: ['نانو', 'طب', 'تشخيص', 'كيمياء'],
    budget: '20,000 ج.م',
    votesCount: 15,
    proposalsCount: 6,
  ),
];

const fallbackLabs = <AcademicLab>[
  AcademicLab(
    name: 'مختبر النانو',
    location: 'كلية العلوم - جامعة القاهرة',
    city: 'القاهرة',
    university: 'جامعة القاهرة',
    equipment: 'مجهر إلكتروني (SEM)',
    tags: ['نانو', 'علوم', 'كيمياء', 'مواد'],
    ratingAvg: 4.6,
    ratingsCount: 28,
    defaultWaitDays: 2,
    equipmentList: [
      LabEquipment(
        id: 'sem',
        name: 'مجهر إلكتروني (SEM)',
        code: 'SEM',
        costPerSession: 800,
        durationMinutes: 120,
        waitDays: 2,
        storeCategoryTitle: 'متجر كيميائي',
      ),
      LabEquipment(
        id: 'xrd',
        name: 'مطياف الأشعة السينية (XRD)',
        code: 'XRD',
        costPerSession: 600,
        durationMinutes: 90,
        waitDays: 3,
        storeCategoryTitle: 'متجر كيميائي',
      ),
    ],
  ),
  AcademicLab(
    name: 'معمل التحليل',
    location: 'مركز البحوث - جامعة عين شمس',
    city: 'القاهرة',
    university: 'جامعة عين شمس',
    equipment: 'جهاز NMR',
    tags: ['تحليل', 'كيمياء', 'مختبر', 'علوم'],
    ratingAvg: 4.3,
    ratingsCount: 15,
    defaultWaitDays: 4,
    equipmentList: [
      LabEquipment(
        id: 'nmr',
        name: 'جهاز الرنين المغناطيسي NMR',
        code: 'NMR',
        costPerSession: 1200,
        durationMinutes: 120,
        waitDays: 4,
        storeCategoryTitle: 'متجر كيميائي',
      ),
      LabEquipment(
        id: 'hplc',
        name: 'كروماتوغرافيا HPLC',
        code: 'HPLC',
        costPerSession: 450,
        durationMinutes: 90,
        waitDays: 2,
        storeCategoryTitle: 'متجر كيميائي',
      ),
    ],
  ),
  AcademicLab(
    name: 'معمل الذكاء الاصطناعي',
    location: 'كلية الحاسبات - جامعة الملك سعود',
    city: 'الرياض',
    university: 'جامعة الملك سعود',
    equipment: 'خوادم GPU للتعلم العميق',
    tags: ['ذكاء', 'بيانات', 'حاسب', 'تعلم'],
    ratingAvg: 4.8,
    ratingsCount: 42,
    defaultWaitDays: 1,
    equipmentList: [
      LabEquipment(
        id: 'gpu-cluster',
        name: 'خوادم GPU للتعلم العميق',
        code: 'GPU',
        costPerSession: 300,
        durationMinutes: 180,
        waitDays: 1,
        storeCategoryTitle: 'متجر هندسي',
      ),
    ],
  ),
];

const fallbackContent = AcademicContent(
  supervisors: fallbackSupervisors,
  ideas: fallbackResearchIdeas,
  labs: fallbackLabs,
);
