import 'academic_models.dart';

const fallbackSupervisors = <AcademicSupervisor>[
  AcademicSupervisor(
    name: 'أ.د. عادل محمود',
    university: 'جامعة القاهرة',
    speciality: 'هندسة مدنية ونانو',
    bio: 'مخترع وباحث في تكنولوجيا المواد الدقيقة والنانو.',
    faculty: 'كلية الهندسة',
    category: 'Engineering',
    tags: ['هندسة', 'مدني', 'نانو', 'مواد'],
    methodologies: ['كمي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'د. هدى الشافعي',
    university: 'جامعة عين شمس',
    speciality: 'هندسة معمارية وذكاء اصطناعي',
    bio: 'متخصصة في معالجة اللغات الطبيعية والتعلم العميق.',
    faculty: 'كلية الهندسة',
    category: 'Engineering',
    tags: ['هندسة', 'معماري', 'ذكاء', 'حاسب'],
    methodologies: ['كمي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'أ.د. سارة علي',
    university: 'جامعة الملك سعود',
    speciality: 'كيمياء عضوية',
    bio: 'أبحاث متقدمة في الكيمياء العضوية والتطبيقات الطبية.',
    faculty: 'كلية العلوم',
    category: 'Science',
    tags: ['كيمياء', 'علوم', 'طب', 'تحليل'],
    methodologies: ['كمي'],
  ),
  AcademicSupervisor(
    name: 'أ.د. مجدي يعقوب',
    university: 'مركز القلب',
    speciality: 'جراحة قلب',
    bio: 'خبير في جراحات القلب المعقدة والأبحاث السريرية.',
    faculty: 'كلية الطب',
    category: 'Medicine',
    tags: ['طب', 'قلب', 'جراحة', 'سريري'],
    methodologies: ['كمي', 'نوعي'],
  ),
  AcademicSupervisor(
    name: 'المستشار أحمد فتحي',
    university: 'جامعة القاهرة',
    speciality: 'قانون دولي',
    bio: 'خبرة واسعة في القانون الدولي والتحكيم.',
    faculty: 'كلية الحقوق',
    category: 'Law',
    tags: ['قانون', 'دولي', 'حقوق'],
    methodologies: ['نوعي', 'مختلط'],
  ),
  AcademicSupervisor(
    name: 'أ.د. محمد أحمد',
    university: 'جامعة القاهرة',
    speciality: 'ذكاء اصطناعي وعلم بيانات',
    bio: 'خبير في تحليل البيانات الضخمة والرؤية الحاسوبية.',
    faculty: 'كلية الحاسبات',
    category: 'CS',
    tags: ['ذكاء', 'بيانات', 'حاسب', 'برمجة'],
    methodologies: ['كمي'],
  ),
];

const fallbackResearchIdeas = <AcademicResearchIdea>[
  AcademicResearchIdea(
    title: 'نظام مرور ذكي',
    provider: 'وزارة النقل',
    details: 'تطوير خوارزميات للتحكم في الإشارات وتحليل حركة المرور.',
    tags: ['مرور', 'ذكاء', 'هندسة', 'تحكم'],
    budget: '15,000 ج.م',
    votesCount: 12,
    proposalsCount: 4,
  ),
  AcademicResearchIdea(
    title: 'طاقة شمسية',
    provider: 'شركة الكهرباء',
    details: 'دراسة تأثير الحرارة على كفاءة الألواح الشمسية.',
    tags: ['طاقة', 'شمسية', 'هندسة', 'كهرباء'],
    budget: '10,000 ج.م',
    votesCount: 8,
    proposalsCount: 2,
  ),
  AcademicResearchIdea(
    title: 'تطبيقات النانو في الطب',
    provider: 'مركز الأبحاث الطبية',
    details: 'استخدام تقنيات النانو في التشخيص المبكر.',
    tags: ['نانو', 'طب', 'تشخيص', 'كيمياء'],
    budget: '20,000 ج.م',
    votesCount: 15,
    proposalsCount: 6,
  ),
];

const fallbackLabs = <AcademicLab>[
  AcademicLab(
    name: 'مركز تحليل المواد — جامعة القاهرة',
    location: 'كلية العلوم — حرم جامعة القاهرة',
    city: 'القاهرة',
    university: 'جامعة القاهرة',
    equipment: 'SEM, XRD, FTIR',
    labType: 'core_facility',
    category: 'Science',
    facultyId: 'Science',
    facultyNameAr: 'كلية العلوم',
    description:
        'منشأة تحليل مركزية تقبل عينات من جميع التخصصات: مواد، كيمياء، صيدلة، طب، هندسة.',
    acceptsExternalSamples: true,
    tags: ['تحليل', 'مواد', 'كيمياء', 'نانو', 'علوم'],
    ratingAvg: 4.7,
    ratingsCount: 56,
    defaultWaitDays: 3,
    sampleServices: [
      SampleAnalysisService(
        id: 'sem',
        name: 'Microscopy SEM',
        description: 'مجهر إلكتروني — morphology & EDX',
        specialties: ['Science', 'Engineering', 'Medicine'],
        sampleTypes: ['مسحوق', 'مواد صلبة', 'أغشية رقيقة'],
        turnaroundDays: 3,
        priceFrom: 750,
      ),
      SampleAnalysisService(
        id: 'xrd',
        name: 'X-Ray Diffraction XRD',
        description: 'تحليل بنية بلورية',
        specialties: ['Science', 'Engineering', 'Pharmacy'],
        sampleTypes: ['مسحوق', 'مواد صلبة'],
        turnaroundDays: 4,
        priceFrom: 600,
      ),
      SampleAnalysisService(
        id: 'ftir',
        name: 'FTIR Spectroscopy',
        description: 'تحليل مجموعات وظيفية',
        specialties: ['Science', 'Pharmacy', 'Agriculture'],
        sampleTypes: ['سوائل', 'مسحوق', 'أغشية'],
        turnaroundDays: 2,
        priceFrom: 350,
      ),
    ],
    equipmentList: [
      LabEquipment(
        id: 'sem',
        name: 'مجهر إلكتروني (SEM)',
        code: 'SEM',
        costPerSession: 800,
        durationMinutes: 120,
        waitDays: 2,
        storeCategoryTitle: 'متجر كيميائي',
      ),
      LabEquipment(
        id: 'xrd',
        name: 'مطياف الأشعة السينية (XRD)',
        code: 'XRD',
        costPerSession: 600,
        durationMinutes: 90,
        waitDays: 3,
        storeCategoryTitle: 'متجر كيميائي',
      ),
    ],
  ),
  AcademicLab(
    name: 'مركز البحوث الطبية — عين شمس',
    location: 'مستشفى عين شمس التخصصي',
    city: 'القاهرة',
    university: 'جامعة عين شمس',
    equipment: 'HPLC, PCR, Histopathology',
    labType: 'research_center',
    category: 'Medicine',
    facultyId: 'Medicine',
    facultyNameAr: 'كلية الطب',
    description:
        'مركز بحوث طبي يستقبل عينات سريرية وبيولوجية للتحليل والتشخيص البحثي.',
    acceptsExternalSamples: true,
    tags: ['طب', 'تحليل', 'أحياء', 'سريري', 'مختبر'],
    ratingAvg: 4.5,
    ratingsCount: 34,
    defaultWaitDays: 5,
    sampleServices: [
      SampleAnalysisService(
        id: 'hplc',
        name: 'HPLC — كمي مركبات',
        description: 'تحديد تركيز مركبات في سوائل biologiques',
        specialties: ['Medicine', 'Pharmacy', 'Science'],
        sampleTypes: ['سوائل', 'غذاء/دواء'],
        turnaroundDays: 5,
        priceFrom: 900,
      ),
      SampleAnalysisService(
        id: 'pcr',
        name: 'PCR / qPCR',
        description: 'تضخيم وت quantification DNA/RNA',
        specialties: ['Medicine', 'Science', 'Agriculture'],
        sampleTypes: ['أنسجة حيوية', 'سوائل'],
        turnaroundDays: 7,
        priceFrom: 1200,
      ),
      SampleAnalysisService(
        id: 'histology',
        name: 'Histopathology',
        description: 'تحضير شرائح وتلوين نسيجي',
        specialties: ['Medicine', 'Veterinary'],
        sampleTypes: ['أنسجة حيوية'],
        turnaroundDays: 10,
        priceFrom: 500,
      ),
    ],
    equipmentList: [
      LabEquipment(
        id: 'hplc',
        name: 'كروماتوغرافيا HPLC',
        code: 'HPLC',
        costPerSession: 450,
        durationMinutes: 90,
        waitDays: 2,
        storeCategoryTitle: 'متجر كيميائي',
      ),
    ],
  ),
  AcademicLab(
    name: 'مركز تحليل التربة والمياه — المنصورة',
    location: 'كلية الزراعة — جامعة المنصورة',
    city: 'المنصورة',
    university: 'جامعة المنصورة',
    equipment: 'ICP, TOC, Microbiology',
    labType: 'research_center',
    category: 'Agriculture',
    facultyId: 'Agriculture',
    facultyNameAr: 'كلية الزراعة',
    description: 'تحليل عينات تربة ومياه ومحاصيل لخدمة أبحاث الزراعة والبيئة.',
    acceptsExternalSamples: true,
    tags: ['زراعة', 'بيئة', 'تحليل', 'ماء', 'تربة'],
    ratingAvg: 4.4,
    ratingsCount: 22,
    sampleServices: [
      SampleAnalysisService(
        id: 'soil',
        name: 'تحليل تربة شامل',
        description: 'NPK، pH، EC، organic matter',
        specialties: ['Agriculture', 'Science'],
        sampleTypes: ['ماء/تربة'],
        turnaroundDays: 6,
        priceFrom: 400,
      ),
      SampleAnalysisService(
        id: 'water',
        name: 'تحليل مياه',
        description: 'معايير صالحية وملوثات',
        specialties: ['Agriculture', 'Engineering', 'Medicine'],
        sampleTypes: ['ماء/تربة', 'سوائل'],
        turnaroundDays: 4,
        priceFrom: 350,
      ),
    ],
    equipmentList: [
      LabEquipment(
        id: 'analysis',
        name: 'تحليل تربة ومياه',
        waitDays: 4,
      ),
    ],
  ),
  AcademicLab(
    name: 'معمل الذكاء الاصطناعي — الملك سعود',
    location: 'كلية الحاسبات',
    city: 'الرياض',
    university: 'جامعة الملك سعود',
    equipment: 'خوادم GPU',
    labType: 'university_lab',
    category: 'CS',
    facultyId: 'CS',
    facultyNameAr: 'كلية الحاسبات',
    tags: ['ذكاء', 'بيانات', 'حاسب', 'تعلم'],
    ratingAvg: 4.8,
    ratingsCount: 42,
    defaultWaitDays: 1,
    equipmentList: [
      LabEquipment(
        id: 'gpu-cluster',
        name: 'خوادم GPU للتعلم العميق',
        code: 'GPU',
        costPerSession: 300,
        durationMinutes: 180,
        waitDays: 1,
        storeCategoryTitle: 'متجر هندسي',
      ),
    ],
  ),
];

const fallbackContent = AcademicContent(
  supervisors: fallbackSupervisors,
  ideas: fallbackResearchIdeas,
  labs: fallbackLabs,
);
