// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRSYtziWUVDLASKW3uWEADpCJrmgXiNk',
    appId: '1:741208597895:web:495600d2fb10b110f6df22',
    messagingSenderId: '741208597895',
    projectId: 'acadegate-new',
    authDomain: 'acadegate-new.firebaseapp.com',
    storageBucket: 'acadegate-new.firebasestorage.app',
    measurementId: 'G-2SS6CQLXL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwRewTZfgKsQD0o9Ujba2kn9sV0bNXRpw',
    appId: '1:741208597895:android:db992ab4724c046ff6df22',
    messagingSenderId: '741208597895',
    projectId: 'acadegate-new',
    storageBucket: 'acadegate-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_f8qLCLOcT1r5zLXJexJRs-iRiI5QhIc',
    appId: '1:741208597895:ios:c73e66b6d640814ff6df22',
    messagingSenderId: '741208597895',
    projectId: 'acadegate-new',
    storageBucket: 'acadegate-new.firebasestorage.app',
    iosBundleId: 'com.example.acadegate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_f8qLCLOcT1r5zLXJexJRs-iRiI5QhIc',
    appId: '1:741208597895:ios:c73e66b6d640814ff6df22',
    messagingSenderId: '741208597895',
    projectId: 'acadegate-new',
    storageBucket: 'acadegate-new.firebasestorage.app',
    iosBundleId: 'com.example.acadegate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADRSYtziWUVDLASKW3uWEADpCJrmgXiNk',
    appId: '1:741208597895:web:46ed47921505270ff6df22',
    messagingSenderId: '741208597895',
    projectId: 'acadegate-new',
    authDomain: 'acadegate-new.firebaseapp.com',
    storageBucket: 'acadegate-new.firebasestorage.app',
    measurementId: 'G-1ZJS9DVVY1',
  );
}
