import '../store_categories.dart';

/// Curated Egyptian academic/lab suppliers for AcadeGate Store.
///
/// [categoryIds] must stay tight: primary specialty first, optional secondary only.
class EgyptStoreSupplier {
  final String id;
  final String nameAr;
  final String nameEn;
  final String website;
  final String email;
  final String phone;
  final String whatsapp;
  final String city;
  final String address;
  final List<String> focusAreas;
  /// Store category ids — keep focused (1–2 max).
  final List<String> categoryIds;
  final String? wooCommerceBaseUrl;
  final String defaultCategoryTitle;
  final bool productSyncEnabled;
  /// Optional hard cap (debug only). Null = pull full WooCommerce catalog.
  final int? syncMaxProducts;
  /// True only when the supplier has an approved Partner relationship on AcadeGate.
  final bool isPartner;
  /// Directory trust: unverified | contacted | verified | claimed
  final String directoryStatus;
  /// Human-readable provenance for directory listings.
  final String dataSourceLabelAr;
  final String dataSourceLabelEn;
  /// ISO date (yyyy-MM-dd) of last human/catalog verification.
  final String lastVerifiedIso;

  const EgyptStoreSupplier({
    required this.id,
    required this.nameAr,
    required this.nameEn,
    required this.website,
    this.email = '',
    this.phone = '',
    this.whatsapp = '',
    this.city = '',
    this.address = '',
    this.focusAreas = const [],
    this.categoryIds = const ['general'],
    this.wooCommerceBaseUrl,
    this.defaultCategoryTitle = 'مستلزمات عامة',
    this.productSyncEnabled = false,
    this.syncMaxProducts,
    this.isPartner = false,
    this.directoryStatus = 'unverified',
    this.dataSourceLabelAr = 'دليل عام من مواقع الموردين المعلنة',
    this.dataSourceLabelEn = 'Public directory from published supplier websites',
    this.lastVerifiedIso = '2026-03-01',
  });

  String get displayContact {
    final parts = <String>[
      if (phone.isNotEmpty) '\u200E$phone',
      if (whatsapp.isNotEmpty && whatsapp != phone) '\u200Eواتساب: $whatsapp',
      if (email.isNotEmpty) '\u200E$email',
      if (website.isNotEmpty) '\u200E$website',
    ];
    return parts.join(' · ');
  }

  String dataSourceLabel(bool isAr) =>
      isAr ? dataSourceLabelAr : dataSourceLabelEn;

  String get resolvedDirectoryStatus {
    // Curated catalog "partner" flag → Confirmed (not Managed Verified).
    if (isPartner) return 'verified';
    return directoryStatus;
  }

  Map<String, dynamic> toFirestoreMap({required DateTime? syncedAt}) {
    final status = resolvedDirectoryStatus;
    // Partner commerce flags only for Managed Verified (admin-approved claim).
    final trusted = status == 'managed_verified';
    return {
      'id': id,
      'nameAr': nameAr,
      'nameEn': nameEn,
      'name': nameAr,
      'website': website,
      'email': email,
      'phone': phone,
      'whatsapp': whatsapp,
      'city': city,
      'address': address,
      'focusAreas': focusAreas,
      'categoryIds': categoryIds,
      'contact': displayContact,
      'defaultCategoryTitle': defaultCategoryTitle,
      'productSyncEnabled': productSyncEnabled,
      'wooCommerceBaseUrl': ?wooCommerceBaseUrl,
      'importSource': 'egypt_suppliers_catalog_2026',
      'dataSource': 'public_web_directory',
      'dataSourceLabelAr': dataSourceLabelAr,
      'dataSourceLabelEn': dataSourceLabelEn,
      'lastVerifiedIso': lastVerifiedIso,
      'directoryStatus': status,
      'isPartner': trusted,
      'isVerifiedSeller': trusted,
      'syncedAt': ?syncedAt,
    };
  }
}

const egyptStoreSuppliersCatalog = <EgyptStoreSupplier>[
  // ─── Chemicals ─────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'piochem',
    nameAr: 'بايوكيم — Piochem',
    nameEn: 'Piochem',
    website: 'https://piochem.com/',
    email: 'info@piochem.com',
    phone: '+201205700001',
    city: '6 أكتوبر / الجيزة',
    address: 'AREA 269A, 1st industrial zone, 6th of October, Giza',
    focusAreas: ['كيميائيات', 'مذيبات', 'كواشف معامل'],
    categoryIds: ['chemicals'],
    wooCommerceBaseUrl: 'https://piochem.com',
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'cornell_lab',
    nameAr: 'كورنيل لاب — Cornell Lab',
    nameEn: 'Cornell Lab',
    website: 'https://cornelllab.com/',
    email: 'info@cornelllab.com',
    phone: '+201001431106',
    city: 'المعادي / القاهرة',
    address: 'Zahraa El Maadi, Cairo',
    focusAreas: ['كيماويات بحثية', 'زجاجيات', 'مستهلكات'],
    categoryIds: ['chemicals', 'consumables'],
    wooCommerceBaseUrl: 'https://cornelllab.com',
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'trust_scientific',
    nameAr: 'تراست ساينتيفيك — Trust Scientific',
    nameEn: 'Trust Scientific',
    website: 'https://trust-scientific.com/',
    email: 'info@trust-scientific.com',
    city: 'فيصل / الجيزة',
    address: '56 El Eshreen St, Faisal, Giza',
    focusAreas: ['كيماويات بحثية', 'NMR'],
    categoryIds: ['chemicals', 'physics_materials'],
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
  ),
  EgyptStoreSupplier(
    id: 'lct_chemicals',
    nameAr: 'الكيماويات المعملية — LCT',
    nameEn: 'Lab Chemicals Trading Co.',
    website: 'http://www.lct-chemicals.com/',
    phone: '+20227923295',
    city: 'جاردن سيتي / القاهرة',
    address: '12st Dr Handousa, Kasr el Ani, Garden City',
    focusAreas: ['كيماويات معامل', 'صيدلانية'],
    categoryIds: ['chemicals'],
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
  ),
  EgyptStoreSupplier(
    id: 'nile_chem',
    nameAr: 'النيل للكيماويات',
    nameEn: 'Nile Chem',
    website: 'https://nilegroupe.com/ar/nile-chem/',
    city: 'مصر',
    focusAreas: ['كيماويات صناعية', 'كيماويات مختبرات'],
    categoryIds: ['chemicals'],
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
  ),
  EgyptStoreSupplier(
    id: 'perfect_lab',
    nameAr: 'بيرفكت لاب',
    nameEn: 'Perfect Lab',
    website: 'https://perfectlabeg.com/',
    email: 'info@perfectlabeg.com',
    phone: '01146037062',
    whatsapp: '01062207698',
    city: 'السيدة زينب / القاهرة',
    address: '11 Aly Yousef St, Alqasr Al Ayni',
    focusAreas: ['كيماويات', 'زجاجيات'],
    categoryIds: ['chemicals', 'consumables'],
    defaultCategoryTitle: 'مستلزمات ومواد كيميائية وكواشف',
  ),

  // ─── Biology ───────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'igtechnology',
    nameAr: 'آي جي تكنولوجي — IGTechnology',
    nameEn: 'IGTechnology',
    website: 'https://www.igtechnologyeg.com/',
    city: 'مصر',
    focusAreas: ['ELISA', 'PCR', 'زراعة خلايا'],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),
  EgyptStoreSupplier(
    id: 'genetech_egypt',
    nameAr: 'جينيتك — Genetech',
    nameEn: 'Genetech',
    website: 'https://genetech.biz/',
    city: 'مصر',
    focusAreas: [
      'كيماويات بحثية وتقنية حيوية',
      'جينوميات وبروتيوميات',
      'إنزيمات ومعدات معامل',
    ],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),
  EgyptStoreSupplier(
    id: 'biokit_egypt',
    nameAr: 'بيوكيت للبحث العلمي',
    nameEn: 'Biokit for Scientific Research',
    website: 'https://www.biokit-eg.com/',
    email: 'info@biokit-eg.com',
    phone: '03-5262810',
    city: 'الإسكندرية',
    address: 'قصر الحجر، فيكتوريا — الإسكندرية',
    focusAreas: [
      'ELISA وPCR',
      'أجسام مضادة وكواشف',
      'أطقم لونية وكيميائيات بحثية',
    ],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),
  EgyptStoreSupplier(
    id: 'primatech_egypt',
    nameAr: 'برايماتك — Primatech',
    nameEn: 'Primatech',
    website: 'https://primatech.com.eg/',
    phone: '+201285206880',
    city: 'الجيزة',
    address: '4 شارع العشرين، المساحة، الهرم',
    focusAreas: [
      'تنقية أحماض نووية',
      'كواشف PCR وqPCR',
      'بلاستيكيات بيولوجيا جزيئية',
    ],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),
  EgyptStoreSupplier(
    id: 'genome_egypt',
    nameAr: 'جينوم — Genome Molecular',
    nameEn: 'Genome Egypt',
    website: 'https://genome-eg.com/',
    city: 'القاهرة',
    focusAreas: [
      'أطقم PCR وReal-Time PCR',
      'بيولوجيا جزيئية وتشخيص جيني',
      'كواشف معامل بحثية',
    ],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),
  EgyptStoreSupplier(
    id: 'nilegen_egypt',
    nameAr: 'نايل جين — NileGen',
    nameEn: 'NileGen',
    website: 'https://nilegen.com/',
    city: 'مصر',
    focusAreas: [
      'استخلاص DNA وRNA',
      'أطقم بيولوجيا جزيئية محلية',
      'دعم معامل البحث المصرية',
    ],
    categoryIds: ['biology'],
    defaultCategoryTitle: 'بيولوجيا وتقنية حيوية',
  ),

  // ─── Medical ───────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'labtronic',
    nameAr: 'لابترونيك — LABTRONIC',
    nameEn: 'LABTRONIC',
    website: 'https://labtronic-eg.com/',
    email: 'info@labtronic-eg.com',
    phone: '+201090548848',
    whatsapp: '01094557032',
    city: 'مصر',
    focusAreas: ['كواشف طبية', 'اختبارات سريعة', 'أجهزة تحاليل'],
    categoryIds: ['medical'],
    wooCommerceBaseUrl: 'https://labtronic-eg.com',
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'omega_lab_equip',
    nameAr: 'أوميجا للتجهيزات المعملية',
    nameEn: 'Omega Laboratory Equipment',
    website: 'https://ome-ga.com/',
    phone: '01095069944',
    whatsapp: '01095069944',
    city: 'مصر',
    focusAreas: ['أجهزة تحاليل طبية', 'CBC', 'كيمياء دم'],
    categoryIds: ['medical'],
    wooCommerceBaseUrl: 'https://ome-ga.com',
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'delta_medical',
    nameAr: 'دلتا ميديكال',
    nameEn: 'Delta Medical',
    website: 'https://deltamedicalco.com/',
    city: 'مصر',
    focusAreas: ['أجهزة طبية', 'كواشف معامل'],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'arkan_scientech',
    nameAr: 'أركان ساينتك — Arkan Scientech',
    nameEn: 'Arkan Scientech',
    website: 'https://arkanscientech.com/',
    city: 'مصر',
    focusAreas: ['أجهزة معامل طبية', 'كواشف تشخيصية'],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'ultra_diagnostic',
    nameAr: 'ألترا دياجنوستك',
    nameEn: 'Ultra Diagnostic',
    website: 'https://ultradiagnostic-eg.net/',
    city: 'المقطم / القاهرة',
    address: '354, 9 St, District D, Al-Nafoura SQ, Mokattam',
    focusAreas: ['معامل سريرية وتشخيصية'],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'diagnostica_egypt',
    nameAr: 'دياجنوستيكا إيجيبت',
    nameEn: 'Diagnostica Egypt',
    website: 'http://www.diagnosticaegypt.com/',
    email: 'Info@diagnosticaegypt.com',
    phone: '+20222901397',
    city: 'مصر الجديدة / القاهرة',
    address: '30 Yacoub Artin St, Heliopolis',
    focusAreas: ['تشخيص مخبري', 'اختبارات بيطرية'],
    categoryIds: ['medical', 'agriculture'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),

  // ─── Dentistry ─────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'trigroup_dental',
    nameAr: 'تراي جروب — مستلزمات وأجهزة أسنان',
    nameEn: 'Trigroup Dental',
    website: 'https://trigroup-eg.com/',
    phone: '01002658518',
    city: 'القاهرة',
    address: '29 بستان الفاضل، القصر العيني',
    focusAreas: [
      'وحدات أسنان وأوتوكلاف',
      'أشعة وأجهزة ليزر',
      'مواد ومستلزمات طب أسنان',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'safwan_dental',
    nameAr: 'صفوان إيجيبت — أجهزة أسنان',
    nameEn: 'Safwan Egypt',
    website: 'https://safwanegypt.com/',
    email: 'info@safwanegypt.com',
    phone: '+2 33031796',
    city: 'الجيزة',
    address: '41 شارع لبنان، المهندسين',
    focusAreas: [
      'أجهزة أسنان متقدمة',
      'تدريب وتعليم طب الأسنان',
      'مشاريع جامعات وعيادات',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'meditech_dental',
    nameAr: 'ميديتك — طب أسنان رقمي',
    nameEn: 'Meditech Dental',
    website: 'https://meditech-eg.com/',
    city: 'القاهرة',
    focusAreas: [
      'Dentsply Sirona وCEREC',
      'ماسحات داخل الفم وطباعة ثلاثية الأبعاد',
      'مواد وأجهزة عيادات أسنان',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),

  // ─── Nursing / clinical / physio ───────────────────────
  EgyptStoreSupplier(
    id: 'euromed_egypt',
    nameAr: 'يوروميد — مستهلكات طبية وتمريض',
    nameEn: 'Euromed',
    website: 'https://euromed.com.eg/',
    email: 'sales@euromed.com.eg',
    phone: '+20 2 2272 5953',
    city: 'مدينة نصر / القاهرة',
    address: 'المنطقة الحرة، مدينة نصر',
    focusAreas: [
      'قفازات وسرنجات وقساطر',
      'مستهلكات تمريض وعدوى',
      'علاج تنفسي وتسريب وريدي',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'cairo_medical_equip',
    nameAr: 'كايرو ميديكال — أجهزة مستشفيات',
    nameEn: 'Cairo Medical',
    website: 'https://cairo-medical.com/',
    email: 'info@cairo-medical.com',
    phone: '+202 275 10 248',
    city: 'المعادي / القاهرة',
    address: '25 شارع 10، المعادي',
    focusAreas: [
      'مراقبين ومزيلات رجفان',
      'أجهزة سريرية للمستشفيات',
      'صيانة ودعم فني',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'surgimed_egypt',
    nameAr: 'سيرجيميد — أدوات جراحية',
    nameEn: 'SURGIMED',
    website: 'https://surgimed.com.eg/',
    email: 'management@surgimed.com.eg',
    city: 'القاهرة',
    address: '14 عزيز الدين محمد عطية',
    focusAreas: [
      'أدوات جراحية دقيقة',
      'خيوط وإبر جراحية',
      'مستلزمات غرف عمليات',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'lmc_physio',
    nameAr: 'لايف ميديكال كونسلت — علاج طبيعي',
    nameEn: 'Life Medical Consult',
    website: 'https://lmc-eg.com/',
    phone: '+(202) 2685 0425',
    city: 'القاهرة',
    focusAreas: [
      'أجهزة علاج طبيعي وإعادة تأهيل',
      'كهرباء علاجية وموجات فوق صوتية',
      'تجهيز عيادات علاج طبيعي',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),
  EgyptStoreSupplier(
    id: 'intercheim_physio',
    nameAr: 'إنترخيم — علاج طبيعي ولياقة',
    nameEn: 'Intercheim',
    website: 'https://intercheim.com/',
    city: 'مصر',
    focusAreas: [
      'أجهزة علاج طبيعي',
      'معدات إعادة تأهيل',
      'أجهزة لياقة علاجية',
    ],
    categoryIds: ['medical'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),

  // ─── Agriculture / vet ─────────────────────────────────
  EgyptStoreSupplier(
    id: 'biolab_pharma',
    nameAr: 'بيولاب فارما إيجي',
    nameEn: 'Biolab Pharma Egy',
    website: 'https://biolabpharma-egy.com/',
    city: 'مصر',
    focusAreas: ['تشخيص بيطري', 'أعلاف'],
    categoryIds: ['agriculture'],
    defaultCategoryTitle: 'زراعة وبيطري',
  ),
  EgyptStoreSupplier(
    id: 'technoscience_agri',
    nameAr: 'تكنو سينس للمستلزمات الزراعية',
    nameEn: 'Techno Science Agri',
    website: 'https://technoscience-agri.com/home/',
    city: 'مصر',
    focusAreas: ['مستلزمات إنتاج زراعي'],
    categoryIds: ['agriculture'],
    defaultCategoryTitle: 'زراعة وبيطري',
  ),
  EgyptStoreSupplier(
    id: 'pharmachem_int',
    nameAr: 'فارما كيم إنترناشونال',
    nameEn: 'PharmaChem International',
    website: 'https://www.pharmachem-int.com/',
    city: 'مصر',
    focusAreas: ['صحة حيوانية', 'إضافات أعلاف'],
    categoryIds: ['agriculture'],
    defaultCategoryTitle: 'زراعة وبيطري',
  ),
  EgyptStoreSupplier(
    id: 'imc_egypt',
    nameAr: 'آي إم سي إيجيبت — IMC',
    nameEn: 'IMC Egypt',
    website: 'https://www.imcwakeel.com/',
    city: 'مصر',
    focusAreas: ['سلامة أعلاف وغذاء', 'ELISA دواجن'],
    categoryIds: ['agriculture'],
    defaultCategoryTitle: 'زراعة وبيطري',
  ),
  EgyptStoreSupplier(
    id: 'mabrouk_eng',
    nameAr: 'مبروك الدولية للصناعات الهندسية',
    nameEn: 'Mabrouk International',
    website: 'https://mabroukegypt.net/ar/',
    city: 'مصر',
    focusAreas: ['معدات زراعية وهندسية'],
    categoryIds: ['agriculture', 'engineering'],
    defaultCategoryTitle: 'زراعة وبيطري',
  ),

  // ─── Engineering / electronics ─────────────────────────
  EgyptStoreSupplier(
    id: 'makers_electronics',
    nameAr: 'ميكرز إلكترونكس — Makers',
    nameEn: 'Makers Electronics',
    website: 'https://makerselectronics.com/',
    email: 'info@makerselectronics.com',
    phone: '+20248813824',
    whatsapp: '01211981188',
    city: 'الإسكندرية',
    address: '158 شارع الحرية، الإبراهيمية',
    focusAreas: ['Arduino', 'مكونات إلكترونية', 'أجهزة قياس', 'IoT'],
    categoryIds: ['engineering', 'computing'],
    wooCommerceBaseUrl: 'https://makerselectronics.com',
    defaultCategoryTitle: 'هندسة وإلكترونيات',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'am_electronics',
    nameAr: 'إيه إم إلكترونكس — AM Electronics',
    nameEn: 'AM Electronics',
    website: 'https://am-electronics.com/',
    city: 'مصر',
    focusAreas: ['مشاريع جامعية', 'Arduino', 'روبوتات', 'CNC / طباعة ثلاثية'],
    categoryIds: ['engineering'],
    wooCommerceBaseUrl: 'https://am-electronics.com',
    defaultCategoryTitle: 'هندسة وإلكترونيات',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'ekostra',
    nameAr: 'إيكوسترا إلكترونكس',
    nameEn: 'Ekostra Electronics',
    website: 'https://ekostra.com/',
    city: 'التجمع الأول / القاهرة',
    focusAreas: ['Arduino', 'حساسات', 'لوحات تطوير'],
    categoryIds: ['engineering'],
    wooCommerceBaseUrl: 'https://ekostra.com',
    defaultCategoryTitle: 'هندسة وإلكترونيات',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'ram_electronics',
    nameAr: 'رام للإلكترونيات',
    nameEn: 'RAM Electronics',
    website: 'https://www.ram.com.eg/',
    email: 'sales@ram-electronics.com',
    phone: '+20227960551',
    city: 'باب اللوق / القاهرة',
    address: '32 شارع الفلكي، باب اللوق',
    focusAreas: ['مكونات إلكترونية', 'أجهزة قياس', 'Raspberry Pi'],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'el_gammal_electronics',
    nameAr: 'الجمّال للإلكترونيات',
    nameEn: 'El Gammal Electronics',
    website: 'https://elgammalelectronic.com/',
    email: 'support@elgammalelectronic.com',
    city: 'مصر',
    focusAreas: ['مكونات', 'أدوات قياس', 'لوحات تطوير'],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'met_egypt',
    nameAr: 'الموارد للهندسة والتجارة — MET',
    nameEn: 'MET Egypt',
    website: 'https://www.met-eg.org/',
    email: 'info@met-eg.com',
    phone: '01223033988',
    city: 'مصر',
    focusAreas: ['أتمتة صناعية', 'حساسات', 'محركات', 'لوحات تحكم'],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'best_lab_eg',
    nameAr: 'بست لاب للتجهيزات المعملية',
    nameEn: 'Best Lab',
    website: 'https://best-lab.org/',
    city: 'القاهرة',
    address: '21 شارع المواردي، القصر العيني',
    focusAreas: ['تجهيز معامل', 'أجهزة', 'صيانة'],
    categoryIds: ['engineering', 'medical'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'meslo_egypt',
    nameAr: 'ميسلو إيجيبت — MESLO',
    nameEn: 'MESLO Egypt',
    website: 'https://meslo.com.eg/',
    city: 'مصر',
    focusAreas: ['أجهزة علمية هندسية', 'تحليل طيفي', 'كروماتوجرافيا'],
    categoryIds: ['engineering', 'instruments', 'physics_materials'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'egs_egypt',
    nameAr: 'المجموعة المصرية للأنظمة — EGS',
    nameEn: 'Egyptian Group Systems',
    website: 'https://egs.com.eg/',
    city: 'مصر',
    focusAreas: ['أجهزة معامل', 'مواد', 'حلول مختبرية'],
    categoryIds: ['engineering', 'instruments'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'eciss_egypt',
    nameAr: 'الشركة المصرية للخدمات الصناعية والعلمية',
    nameEn: 'ECISS',
    website: 'https://www.eciss.com.eg/',
    city: 'مصر',
    focusAreas: ['اختبارات صناعية', 'قياس', 'أجهزة معامل'],
    categoryIds: ['engineering', 'instruments'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),

  // ─── Civil / mechanical / materials testing ────────────
  EgyptStoreSupplier(
    id: 'control_engineering_egypt',
    nameAr: 'كنترول إنجينيرنج — معامل مدنية',
    nameEn: 'Control Engineering',
    website: 'https://controleng.org/',
    city: 'مصر',
    focusAreas: [
      'اختبار تربة وأسمنت وخرسانة',
      'أجهزة معامل إنشاءات',
      'أسفلت ومواد بناء',
    ],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'ags_geotech_egypt',
    nameAr: 'إيه جي إس — أنظمة جيوتقنية',
    nameEn: 'Automatic Geotechnical Systems (AGS)',
    website: 'https://ags-eg.com/',
    email: 'sales@ags-eg.com',
    phone: '+20 1157111847',
    whatsapp: '+201157111847',
    city: '6 أكتوبر / الجيزة',
    address: 'مدينة الفردوس، 6 أكتوبر',
    focusAreas: [
      'اختبارات جيوتقنية آلية',
      'ضغط خرسانة وقص تربة',
      'أجهزة معامل هندسة مدنية',
    ],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'pact_egypt',
    nameAr: 'بكت مصر — أجهزة جودة واختبار',
    nameEn: 'PACT Egypt',
    website: 'https://pact-egypt.com/',
    city: 'مصر',
    focusAreas: [
      'اختبار مواد وبلاستيك ومعادن',
      'أجهزة هندسة مدنية',
      'ضبط جودة معامل',
    ],
    categoryIds: ['engineering'],
    defaultCategoryTitle: 'هندسة وإلكترونيات',
  ),
  EgyptStoreSupplier(
    id: 'bardissi_medical',
    nameAr: 'برديسي ميديكال — أجهزة ومعامل',
    nameEn: 'Bardissi Medical',
    website: 'https://bardissi.com/',
    city: 'مصر',
    focusAreas: [
      'أجهزة معامل طبية وبحثية',
      'مستهلكات زراعة خلايا',
      'كواشف وكيماويات سريرية',
    ],
    categoryIds: ['medical', 'biology'],
    defaultCategoryTitle: 'طبي وصيدلي وسريري',
  ),

  // ─── Physics / materials ───────────────────────────────
  EgyptStoreSupplier(
    id: 'gemicatech',
    nameAr: 'جيميكاتيك — Gemicatech',
    nameEn: 'Gemicatech',
    website: 'https://gemicatech.com/',
    city: 'مصر',
    focusAreas: ['أجهزة تحليلية', 'حلول علمية'],
    categoryIds: ['instruments', 'physics_materials'],
    defaultCategoryTitle: 'أجهزة وأدوات قياس',
  ),
  EgyptStoreSupplier(
    id: 'scientific_services_egypt',
    nameAr: 'ساينتيفيك سيرفيسز — اختبار مواد',
    nameEn: 'Scientific Services',
    website: 'https://www.scientificserv.com/',
    city: 'القاهرة الجديدة',
    focusAreas: [
      'أجهزة اختبار المواد (Instron)',
      'تحضير عينات (Struers)',
      'NDT لمواد البناء وهندسة ميكانيكية',
    ],
    categoryIds: ['physics_materials', 'engineering'],
    defaultCategoryTitle: 'فيزياء ومواد',
  ),
  EgyptStoreSupplier(
    id: 'els_egypt',
    nameAr: 'خدمات البيئة والمعامل — ELS',
    nameEn: 'Environmental & Lab Services',
    website: 'https://els-eg.com/',
    city: 'مصر',
    focusAreas: [
      'أجهزة تحليلية ومواد',
      'رصد بيئي',
      'حلول معامل بحثية وصناعية',
    ],
    categoryIds: ['physics_materials'],
    defaultCategoryTitle: 'فيزياء ومواد',
  ),

  // ─── Consumables ───────────────────────────────────────
  EgyptStoreSupplier(
    id: 'lab_supply_group',
    nameAr: 'لاب سابلاي جروب',
    nameEn: 'Lab Supply Group',
    website: 'https://lab-supply.net/',
    email: 'sales@lab-supply.net',
    phone: '+201050227430',
    whatsapp: '+201018768333',
    city: 'مصر',
    focusAreas: ['مستهلكات', 'أجهزة معامل', 'كيماويات'],
    categoryIds: ['consumables', 'instruments'],
    wooCommerceBaseUrl: 'https://lab-supply.net',
    defaultCategoryTitle: 'مستهلكات وأدوات مختبر',
    productSyncEnabled: true,
  ),
  EgyptStoreSupplier(
    id: 'elemental_eg',
    nameAr: 'إليمنتال — Elemental',
    nameEn: 'Elemental',
    website: 'https://elementaleg.com/',
    email: 'info@elementaleg.com',
    phone: '+201067828381',
    city: 'مدينة نصر / القاهرة',
    focusAreas: ['زجاجيات', 'بلاستيك معامل', 'مستهلكات'],
    categoryIds: ['consumables'],
    defaultCategoryTitle: 'مستهلكات وأدوات مختبر',
  ),
  EgyptStoreSupplier(
    id: 'lab_supply_egypt',
    nameAr: 'لاب سابلاي إيجيبت',
    nameEn: 'Lab Supply Egypt',
    website: 'https://labsupplyegypt.com/',
    city: 'مصر',
    focusAreas: ['مستلزمات معامل'],
    categoryIds: ['consumables'],
    defaultCategoryTitle: 'مستهلكات وأدوات مختبر',
  ),

  // ─── Instruments ───────────────────────────────────────
  EgyptStoreSupplier(
    id: 'sam_lab_egypt',
    nameAr: 'سام لاب إيجيبت',
    nameEn: 'SAM Lab Egypt',
    website: 'https://samlabegypt.com/',
    email: 'info@samlabegypt.com',
    phone: '+201001012695',
    city: 'حلميّة الزيتون / القاهرة',
    address: '3 El Bishry St, Helmyete El Zitoun',
    focusAreas: ['أجهزة علمية ومعملية'],
    categoryIds: ['instruments'],
    defaultCategoryTitle: 'أجهزة وأدوات قياس',
  ),
  EgyptStoreSupplier(
    id: 'lab_egypt',
    nameAr: 'لاب إيجيبت — Lab Egypt',
    nameEn: 'Lab Egypt',
    website: 'https://labegypt.com/',
    city: 'مصر',
    focusAreas: ['أجهزة قياس pH / EC / DO', 'قياس ميداني وبيئي'],
    categoryIds: ['instruments', 'field'],
    defaultCategoryTitle: 'أجهزة وأدوات قياس',
  ),

  // ─── Safety ────────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'first_env',
    nameAr: 'فرست للاستشارات والبيئة',
    nameEn: 'FIRST Company',
    website: 'https://www.first-env.com/',
    city: 'مصر',
    focusAreas: ['سلامة شخصية', 'معايرة', 'حماية'],
    categoryIds: ['safety'],
    defaultCategoryTitle: 'سلامة ومعدات وقاية',
  ),
  EgyptStoreSupplier(
    id: 'yehia_abdin_safety',
    nameAr: 'يحيى عابدين — معدات وقاية',
    nameEn: 'Yehia Abdin Co.',
    website: 'https://yehiaco.com/',
    city: 'مصر',
    focusAreas: [
      'PPE من الرأس للقدم',
      'معدات إطفاء',
      'علامات تجارية عالمية (3M، Ansell، Uvex)',
    ],
    categoryIds: ['safety'],
    defaultCategoryTitle: 'سلامة ومعدات وقاية',
  ),
  EgyptStoreSupplier(
    id: 'aman_safety_egypt',
    nameAr: 'أمان إيجيبت — AMAN Safety',
    nameEn: 'AMAN Egypt',
    website: 'https://www.aman-safety.com/',
    city: 'القاهرة',
    focusAreas: [
      'معدات وقاية شخصية',
      'سلامة حريق وطوارئ',
      'حلول HSSE',
    ],
    categoryIds: ['safety'],
    defaultCategoryTitle: 'سلامة ومعدات وقاية',
  ),
  EgyptStoreSupplier(
    id: 'icis_safety_egypt',
    nameAr: 'الآيسس للسلامة الصناعية — ICIS',
    nameEn: 'ICIS Safety',
    website: 'https://icissafety.com/',
    city: 'القاهرة',
    focusAreas: [
      'نظارات وقفازات وخوذات',
      'إطفاء حريق',
      'كواشف غاز وحماية بيئة',
    ],
    categoryIds: ['safety'],
    defaultCategoryTitle: 'سلامة ومعدات وقاية',
  ),
  EgyptStoreSupplier(
    id: 'smart_safety_egypt',
    nameAr: 'سمارت سيفتي — Smart Safety',
    nameEn: 'Smart Safety Egypt',
    website: 'https://smartsafety-eg.com/',
    city: 'المعادي / القاهرة',
    address: '3 شارع 291، اللاسلكي، المعادي',
    focusAreas: [
      'PPE صناعي',
      'كشف غاز وإنذار حريق',
      'حماية سقوط وتنفس',
    ],
    categoryIds: ['safety'],
    defaultCategoryTitle: 'سلامة ومعدات وقاية',
  ),

  // ─── Field / survey ────────────────────────────────────
  EgyptStoreSupplier(
    id: 'field_survey_note',
    nameAr: 'أجهزة مساحة ومسح (عبر فرست / لاب إيجيبت)',
    nameEn: 'Survey & field gear contacts',
    website: 'https://www.first-env.com/',
    city: 'مصر',
    focusAreas: ['مسح', 'قياس ميداني', 'بيئة'],
    categoryIds: ['field'],
    defaultCategoryTitle: 'أدوات ميدانية ومسح',
  ),
  EgyptStoreSupplier(
    id: 'surveying_systems_egypt',
    nameAr: 'سيرفيينج سيستمز — أجهزة مساحة',
    nameEn: 'Surveying Systems',
    website: 'https://surveying-systems.com/',
    phone: '0233037389',
    city: 'القاهرة',
    address: 'المهندسين / مدينة نصر',
    focusAreas: [
      'أجهزة مساحة GPS وTotal Station',
      'مسح هيدروغرافي',
      'صيانة ودعم فني',
    ],
    categoryIds: ['field'],
    defaultCategoryTitle: 'أدوات ميدانية ومسح',
  ),
  EgyptStoreSupplier(
    id: 'zone_technologies_egypt',
    nameAr: 'زون تكنولوجيز — Trimble مصر',
    nameEn: 'Zone Technologies',
    website: 'https://zoneegypt.com/',
    phone: '02 25 200 210',
    city: 'المعادي الجديدة / القاهرة',
    focusAreas: [
      'Trimble GNSS ومسح ثلاثي الأبعاد',
      'محطات مساحة وتصوير',
      'حلول GIS ميدانية',
    ],
    categoryIds: ['field'],
    defaultCategoryTitle: 'أدوات ميدانية ومسح',
  ),
  EgyptStoreSupplier(
    id: 'msi_survey_egypt',
    nameAr: 'المصرية لأجهزة المساحة — MSI',
    nameEn: 'MSI Surveying & Instruments',
    website: 'https://msi-eg.com/',
    email: 'Adelomar@msi-eg.com',
    phone: '+20-109-755-0665',
    city: 'مصر',
    focusAreas: [
      'GPS ومحطات مساحة',
      'ماسحات ليزر ثلاثية الأبعاد',
      'معايرة وصيانة أجهزة ميدانية',
    ],
    categoryIds: ['field'],
    defaultCategoryTitle: 'أدوات ميدانية ومسح',
  ),
  // ─── Computing ─────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'itida_dir',
    nameAr: 'هيئة تنمية صناعة تكنولوجيا المعلومات (ITIDA)',
    nameEn: 'ITIDA',
    website: 'https://itida.gov.eg/',
    city: 'مصر',
    focusAreas: ['برمجيات', 'شركات تقنية'],
    categoryIds: ['computing'],
    defaultCategoryTitle: 'حوسبة وبرمجيات بحثية',
  ),
  EgyptStoreSupplier(
    id: 'mcit_egypt',
    nameAr: 'وزارة الاتصالات وتكنولوجيا المعلومات',
    nameEn: 'MCIT Egypt',
    website: 'https://mcit.gov.eg/',
    city: 'مصر',
    focusAreas: ['مبادرات رقمية'],
    categoryIds: ['computing'],
    defaultCategoryTitle: 'حوسبة وبرمجيات بحثية',
  ),
  EgyptStoreSupplier(
    id: 'secc_egypt',
    nameAr: 'مركز جدارة هندسة البرمجيات — SECC',
    nameEn: 'SECC (ITIDA)',
    website: 'https://itida.gov.eg/English/Programs/SECC-Offerings/Pages/default.aspx',
    email: 'info@secc.org.eg',
    city: 'مصر',
    focusAreas: [
      'تدريب واعتماد برمجي',
      'CMMI وAgile وDevOps',
      'رفع كفاءة فرق البحث والتطوير',
    ],
    categoryIds: ['computing'],
    defaultCategoryTitle: 'حوسبة وبرمجيات بحثية',
  ),
  EgyptStoreSupplier(
    id: 'btech_egypt',
    nameAr: 'بي تك — B.TECH',
    nameEn: 'B.TECH Egypt',
    website: 'https://www.btech.com/',
    city: 'مصر',
    focusAreas: [
      'حواسيب ومحطات عمل',
      'ملحقات وعتاد بحثي',
      'شاشات وتخزين',
    ],
    categoryIds: ['computing'],
    defaultCategoryTitle: 'حوسبة وبرمجيات بحثية',
  ),
  EgyptStoreSupplier(
    id: 'two_b_egypt',
    nameAr: 'تو بي — 2B',
    nameEn: '2B Egypt',
    website: 'https://www.2b.com.eg/',
    city: 'مصر',
    focusAreas: [
      'أجهزة حاسب ولابتوب',
      'مكونات وأنظمة',
      'عتاد لمشاريع هندسية وبحثية',
    ],
    categoryIds: ['computing'],
    defaultCategoryTitle: 'حوسبة وبرمجيات بحثية',
  ),

  // ─── Books & academic references (books ONLY — not humanities tools) ───
  EgyptStoreSupplier(
    id: 'auc_press',
    nameAr: 'مطبعة ومكتبات الجامعة الأمريكية بالقاهرة (AUC Press)',
    nameEn: 'AUC Press & Bookstores',
    website: 'https://aucpress.com/',
    email: 'bookstores@aucegypt.edu',
    phone: '+20 2 27975929',
    city: 'القاهرة',
    address: 'تحرير / New Cairo — متاجر AUC Bookstores',
    focusAreas: [
      'نشر كتب أكاديمية',
      'بيع كتب ومقررات',
      'دراسات شرق أوسطية وآثار',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'al_shorouk',
    nameAr: 'مكتبات الشروق',
    nameEn: 'Al Shorouk Bookstores',
    website: 'https://www.shoroukbookstores.com/',
    city: 'مصر',
    focusAreas: ['كتب عربية وأجنبية', 'مراجع ثقافية وأكاديمية'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'gebo',
    nameAr: 'الهيئة المصرية العامة للكتاب',
    nameEn: 'Egyptian General Book Organization',
    website: 'https://gebo.gov.eg/',
    city: 'القاهرة',
    focusAreas: [
      'نشر وبيع كتب عربية',
      'مكتبة الأسرة',
      'معارض الكتاب',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'anglo_egyptian',
    nameAr: 'مكتبة الأنجلو المصرية',
    nameEn: 'Anglo-Egyptian Bookshop',
    website: 'https://www.anglo-egyptian.com/',
    city: 'القاهرة',
    focusAreas: [
      'كتب أكاديمية عربية وإنجليزية',
      'علم نفس وتربية ومقاييس',
      'مراجع جامعية',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'diwan_bookstore',
    nameAr: 'مكتبة ديوان',
    nameEn: 'Diwan Bookstore',
    website: 'https://diwanegypt.com/',
    phone: '01222407084',
    city: 'القاهرة',
    address: 'الزمالك · المعادي · مصر الجديدة · وسط البلد',
    focusAreas: [
      'كتب متعددة اللغات',
      'أدب وعلوم إنسانية',
      'فروع داخل مصر',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'tanmia_bookstore',
    nameAr: 'مكتبة تنمية',
    nameEn: 'Tanmia Bookstore',
    website: 'https://www.instagram.com/tanmiabookstores/',
    phone: '01005029128',
    city: 'القاهرة',
    address: '19 شارع هدى شعراوي، وسط البلد',
    focusAreas: ['كتب عربية', 'أدب وثقافة', 'إصدارات معاصرة'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'ekb_books',
    nameAr: 'بنك المعرفة المصري — كتب ومراجع إلكترونية',
    nameEn: 'Egyptian Knowledge Bank — eBooks & references',
    website: 'https://www.ekb.eg/',
    city: 'مصر',
    focusAreas: [
      'كتب إلكترونية',
      'قواعد مراجع عالمية',
      'وصول عبر الجامعات المصرية',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'eulc',
    nameAr: 'اتحاد مكتبات الجامعات المصرية (EULC)',
    nameEn: 'Egyptian Universities Libraries Consortium',
    website: 'https://scu.eg/en/eksc_units/digital-libraries-unit/',
    city: 'مصر',
    focusAreas: [
      'فهرس موحّد لمكتبات الجامعات',
      'مستودع الرسائل',
      'مصادر إلكترونية بحثية',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'cairo_univ_central_library',
    nameAr: 'المكتبة المركزية الجديدة — جامعة القاهرة',
    nameEn: 'Cairo University New Central Library',
    website: 'https://cl.cu.edu.eg/',
    city: 'القاهرة',
    focusAreas: [
      'كتب ومراجع جامعية',
      'رسائل علمية',
      'خدمات باحثين',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'bibalex_books',
    nameAr: 'مكتبة الإسكندرية — خدمات المكتبة والكتب',
    nameEn: 'Bibliotheca Alexandrina — Library & books',
    website: 'https://www.bibalex.org/',
    city: 'الإسكندرية',
    focusAreas: [
      'مكتبة رقمية',
      'كتب ومراجع',
      'مجموعات بحثية',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'auc_library_books',
    nameAr: 'مكتبة الجامعة الأمريكية — كتالوج البحث (ليس المتجر)',
    nameEn: 'AUC Library catalog (not the bookstore)',
    website: 'https://library.aucegypt.edu/',
    city: 'القاهرة',
    focusAreas: [
      'كتالوج مكتبي جامعي',
      'دوريات وقواعد بيانات',
      'خدمات باحثين وطلاب AUC',
    ],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'ain_shams_library_books',
    nameAr: 'مكتبة جامعة عين شمس',
    nameEn: 'Ain Shams University Library',
    website: 'https://www.asu.edu.eg/',
    city: 'القاهرة',
    focusAreas: ['كتب ومراجع جامعية', 'رسائل وكليات متعددة'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'alex_univ_library_books',
    nameAr: 'مكتبات جامعة الإسكندرية',
    nameEn: 'Alexandria University Libraries',
    website: 'https://alexu.edu.eg/',
    city: 'الإسكندرية',
    focusAreas: ['مكتبات كليات', 'كتب ورسائل جامعية'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'dar_elkotob_publications',
    nameAr: 'دار الكتب والوثائق — إصدارات وبيع مطبوعات',
    nameEn: 'National Library — Publications sales',
    website: 'https://www.darelkotob.gov.eg/',
    city: 'القاهرة',
    focusAreas: ['مطبوعات رسمية', 'كتب تراثية', 'فهارس'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'moe_ebooks',
    nameAr: 'المكتبة الإلكترونية — وزارة التربية والتعليم',
    nameEn: 'MoE Egypt Student eBooks',
    website: 'https://studentbooks.moe.gov.eg/',
    city: 'مصر',
    focusAreas: ['كتب مدرسية إلكترونية', 'مراجع تعليمية'],
    categoryIds: ['books'],
    defaultCategoryTitle: 'كتب ومراجع علمية',
    lastVerifiedIso: '2026-09-20',
  ),

  // ─── Humanities tools / data / archives (NOT retail bookstores) ───
  EgyptStoreSupplier(
    id: 'mandumah',
    nameAr: 'دار المنظومة',
    nameEn: 'Dar Almandumah',
    website: 'https://mandumah.com/',
    city: 'عربي / عبر الجامعات المصرية',
    focusAreas: [
      'رسائل ماجستير ودكتوراه عربية',
      'دوريات محكمة',
      'قواعد تربية وإنسانيات وعلوم اجتماعية',
    ],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'dar_elkotob_archives',
    nameAr: 'دار الكتب والوثائق القومية — أرشيف ومخطوطات',
    nameEn: 'National Library & Archives — manuscripts',
    website: 'https://www.darelkotob.gov.eg/',
    city: 'القاهرة',
    focusAreas: ['وثائق', 'مخطوطات', 'أرشيف بحث إنساني'],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'bibalex_archives',
    nameAr: 'مكتبة الإسكندرية — أرشيف ومشاريع إنسانية',
    nameEn: 'Bibliotheca Alexandrina — archives & humanities',
    website: 'https://www.bibalex.org/',
    city: 'الإسكندرية',
    focusAreas: ['أرشيف رقمي', 'مشاريع بحث إنساني', 'ذاكرة معاصرة'],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'al_azhar_library',
    nameAr: 'مكتبة الأزهر الشريف — مخطوطات وتراث',
    nameEn: 'Al-Azhar Library — manuscripts',
    website: 'https://www.azhar.eg/',
    city: 'القاهرة',
    focusAreas: [
      'مخطوطات وتراث',
      'دراسات إسلامية وإنسانية',
      'خدمات بحث تراثي',
    ],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'ncerd',
    nameAr: 'المركز القومي للبحوث التربوية والتنمية',
    nameEn: 'NCERD — National Center for Educational Research',
    website: 'http://www.ncerd.edu.eg/',
    city: 'القاهرة',
    focusAreas: [
      'بحوث تربوية',
      'مناهج وتطوير تعليم',
      'تقارير للباحثين في التربية',
    ],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'capmas',
    nameAr: 'الجهاز المركزي للتعبئة العامة والإحصاء',
    nameEn: 'CAPMAS',
    website: 'https://www.capmas.gov.eg/',
    city: 'القاهرة',
    focusAreas: [
      'إحصاءات سكانية واجتماعية',
      'بيانات للبحث الاجتماعي',
      'تقارير رسمية',
    ],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),
  EgyptStoreSupplier(
    id: 'idsc',
    nameAr: 'مركز المعلومات ودعم اتخاذ القرار',
    nameEn: 'IDSC Egypt',
    website: 'https://www.idsc.gov.eg/',
    city: 'القاهرة',
    focusAreas: [
      'تقارير سياسات عامة',
      'بيانات وبحوث اجتماعية',
      'دعم باحثين وصنّاع قرار',
    ],
    categoryIds: ['humanities'],
    defaultCategoryTitle: 'إنسانيات وتربية وبحث اجتماعي',
    lastVerifiedIso: '2026-09-20',
  ),

  // ─── Research writing / documentation / thesis print ───
  EgyptStoreSupplier(
    id: 'alwan_stationary',
    nameAr: 'ألوان للقرطاسية والمستلزمات المكتبية',
    nameEn: 'Alwan Stationery',
    website: 'https://alwan.com.eg/',
    email: 'info@alwan.com.eg',
    phone: '19275',
    city: 'مصر',
    focusAreas: [
      'دفاتر وأوراق',
      'أقلام وأدوات كتابة',
      'ملفات وأرشفة',
      'مستلزمات مكتبية للباحث',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),
  EgyptStoreSupplier(
    id: 'zamzam_printing',
    nameAr: 'زمزم للطباعة والتجليد',
    nameEn: 'Zamzam Printing & Binding',
    website: 'https://zamzam.com.eg/',
    phone: '+20 2 27952362',
    whatsapp: '+20 101 221 4422',
    city: 'القاهرة',
    address: '53 شارع نوبار، وسط البلد، القاهرة',
    focusAreas: [
      'طباعة أطروحات ورسائل',
      'تجليد غلاف صلب',
      'طباعة عند الطلب',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),
  EgyptStoreSupplier(
    id: 'salama_printing',
    nameAr: 'سلامة للطباعة',
    nameEn: 'Salama Printing',
    website: 'https://salamaprinting.com/',
    phone: '+20 2 24550391',
    city: 'القاهرة',
    address: 'مصر الجديدة / جسر السويس',
    focusAreas: [
      'طباعة كتب وكتالوجات',
      'تجليد سلكي ومثالي',
      'طباعة مكتبية أكاديمية',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),
  EgyptStoreSupplier(
    id: 'algazera_press',
    nameAr: 'الجزيرة إنترناشونال برس',
    nameEn: 'Al Gazera International Press',
    website: 'https://algazerapress.com/',
    city: 'الجيزة',
    address: 'المهندسين / العجوزة',
    focusAreas: [
      'طباعة رقمية وأوفست',
      'تجليد أطروحات',
      'أرشفة ووثائق',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),
  EgyptStoreSupplier(
    id: 'kayan_print',
    nameAr: 'كيان للطباعة والتجليد',
    nameEn: 'Kayan Print',
    website: 'https://www.kayanprint.store/',
    email: 'kayanofprint@gmail.com',
    phone: '01121499017',
    whatsapp: '01121499017',
    city: 'مصر',
    focusAreas: [
      'طباعة رسائل ماجستير ودكتوراه',
      'تجليد غلاف صلب',
      'طباعة أبحاث وعروض',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),
  EgyptStoreSupplier(
    id: 'gse_stationery',
    nameAr: 'المؤسسة الدولية للورق — GSE',
    nameEn: 'Global Stationery Enterprise',
    website: 'https://www.gse-eg.com/',
    city: 'القاهرة',
    focusAreas: [
      'ورق ومستلزمات مكتبية',
      'توريدات قرطاسية للمؤسسات',
      'مستلزمات توثيق وأرشفة',
    ],
    categoryIds: ['office'],
    defaultCategoryTitle: 'مستلزمات كتابة وتوثيق البحث',
  ),

  // ─── General ───────────────────────────────────────────
  EgyptStoreSupplier(
    id: 'general_lab_hub',
    nameAr: 'مستلزمات عامة للمعامل',
    nameEn: 'General lab supplies hub',
    website: 'https://labsupplyegypt.com/',
    city: 'مصر',
    focusAreas: ['توريدات عامة للمعامل'],
    categoryIds: ['general'],
    defaultCategoryTitle: 'مستلزمات عامة',
  ),
  EgyptStoreSupplier(
    id: 'amazon_egypt',
    nameAr: 'أمازون مصر',
    nameEn: 'Amazon.eg',
    website: 'https://www.amazon.eg/',
    city: 'مصر',
    focusAreas: [
      'مستلزمات عامة ومتنوعة',
      'إلكترونيات وأدوات',
      'توصيل سريع للباحثين',
    ],
    categoryIds: ['general'],
    defaultCategoryTitle: 'مستلزمات عامة',
  ),
  EgyptStoreSupplier(
    id: 'jumia_egypt',
    nameAr: 'جوميا مصر',
    nameEn: 'Jumia Egypt',
    website: 'https://www.jumia.com.eg/',
    city: 'مصر',
    focusAreas: [
      'سوق إلكتروني عام',
      'مستلزمات مكتبية وتقنية',
      'خيارات متعددة للباحث',
    ],
    categoryIds: ['general'],
    defaultCategoryTitle: 'مستلزمات عامة',
  ),
  EgyptStoreSupplier(
    id: 'noon_egypt',
    nameAr: 'نون مصر',
    nameEn: 'noon Egypt',
    website: 'https://www.noon.com/egypt-en/',
    city: 'مصر',
    focusAreas: [
      'مستلزمات عامة',
      'إلكترونيات وأدوات منزلية/مكتبية',
      'توصيل للمنازل والمكاتب',
    ],
    categoryIds: ['general'],
    defaultCategoryTitle: 'مستلزمات عامة',
  ),
  EgyptStoreSupplier(
    id: 'newvip_stationery',
    nameAr: 'نيو في آي بي — مستلزمات عامة',
    nameEn: 'NEW VIP Ltd.',
    website: 'https://newvip.ltd/',
    city: 'مصر',
    focusAreas: [
      'توريدات مكتبية ومؤسسية',
      'مستلزمات عامة بالجملة',
      'إدارة توريد للجامعات والمراكز',
    ],
    categoryIds: ['general'],
    defaultCategoryTitle: 'مستلزمات عامة',
  ),
];

EgyptStoreSupplier? egyptStoreSupplierById(String id) {
  for (final s in egyptStoreSuppliersCatalog) {
    if (s.id == id) return s;
  }
  return null;
}

List<EgyptStoreSupplier> get egyptStoreSuppliersWithProductSync =>
    egyptStoreSuppliersCatalog.where((s) => s.productSyncEnabled).toList();

/// Exact specialty match only — no cross-dumping into unrelated sections.
List<EgyptStoreSupplier> egyptStoreSuppliersForCategory({
  String? categoryId,
  String? categoryTitle,
}) {
  final id = categoryId ??
      storeCategoryByTitle(categoryTitle ?? '')?.id ??
      '';
  if (id.isEmpty) return const [];
  return egyptStoreSuppliersCatalog
      .where((s) => s.categoryIds.contains(id))
      .toList();
}

Map<String, int> egyptStoreSupplierCoverageCounts() {
  final map = <String, int>{};
  for (final c in storeCategories) {
    map[c.id] = egyptStoreSuppliersCatalog
        .where((s) => s.categoryIds.contains(c.id))
        .length;
  }
  return map;
}
